# Generated by Django 3.2.4 on 2021-12-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_auto_20210608_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetup',
            options={'ordering': ['-date']},
        ),
    ]
